"""update users and refresh_tokens

Revision ID: 060b5d731b8b
Revises: 5bb6ee45b627
Create Date: 2026-05-25 23:05:04.990887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '060b5d731b8b'
down_revision: Union[str, None] = '5bb6ee45b627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_unique_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('STUDENT', 'ORGANIZER', 'ADMIN', name='userrole', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_users_student_id', table_name='users')
    op.drop_index('ix_users_wallet_address', table_name='users')
    op.create_unique_constraint(op.f('uq_users_student_id'), 'users', ['student_id'])
    op.create_unique_constraint(op.f('uq_users_wallet_address'), 'users', ['wallet_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_wallet_address'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_student_id'), 'users', type_='unique')
    op.create_index('ix_users_wallet_address', 'users', ['wallet_address'], unique=True)
    op.create_index('ix_users_student_id', 'users', ['student_id'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'ORGANIZER', 'ADMIN', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', type_='unique')
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###
