"""add tables: auctions, bids

Revision ID: 1b4e1c2c7fea
Revises: 26a589a107b2
Create Date: 2026-05-28 22:48:53.571090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4e1c2c7fea'
down_revision: Union[str, None] = '26a589a107b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=150), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lesson_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resource_limit', sa.Integer(), nullable=False),
    sa.Column('blockchain_auction_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='auctionstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_auctions_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auctions')),
    sa.UniqueConstraint('blockchain_auction_id', name=op.f('uq_auctions_blockchain_auction_id'))
    )
    op.create_table('bids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'REFUNDED', 'BURNED', 'CLAIMED', name='bidstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], name=op.f('fk_bids_auction_id_auctions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bids_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bids'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('auctions')
    # ### end Alembic commands ###
