"""add_priv_key_in_user

Revision ID: 5ea492161605
Revises: 7649321baf07
Create Date: 2026-05-26 19:36:34.210223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea492161605'
down_revision: Union[str, None] = '7649321baf07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_private_key', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_private_key')
    # ### end Alembic commands ###
