"""Add projects and user_projects tables

Revision ID: e68905997d62
Revises: 5ea492161605
Create Date: 2026-05-27 19:18:10.710694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e68905997d62'
down_revision: Union[str, None] = '5ea492161605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('organizer_id', sa.Uuid(), nullable=False),
    sa.Column('blockchain_id', sa.BigInteger(), nullable=False),
    sa.Column('refund_rate', sa.Numeric(precision=5, scale=2), server_default='80.00', nullable=False),
    sa.Column('penalty_schedule', postgresql.JSONB(astext_type=sa.Text()), server_default='[10, 20, 30, 50]', nullable=False),
    sa.Column('initial_supply', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], name=op.f('fk_projects_organizer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('blockchain_id', name=op.f('uq_projects_blockchain_id'))
    )
    op.create_table('user_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('token_balance', sa.Numeric(precision=78, scale=0), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_user_projects_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_projects_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_projects')),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_user_project')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
